# Generated by Django 3.2.19 on 2024-11-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Краткое название')),
                ('situation', models.TextField(verbose_name='Ситуация')),
                ('rivalry', models.TextField(verbose_name='Соперничество')),
                ('device', models.TextField(verbose_name='Приспособление')),
                ('avoidance', models.TextField(verbose_name='Избегание')),
                ('compromise', models.TextField(verbose_name='Компромисс')),
                ('cooperation', models.TextField(verbose_name='Сотрудничество')),
            ],
            options={
                'verbose_name': 'ситуация',
                'verbose_name_plural': 'ситуации',
            },
        ),
    ]
