# Generated by Django 3.2.19 on 2024-11-29 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rivalry_answer', models.TextField(verbose_name='Соперничество')),
                ('device_answer', models.TextField(verbose_name='Приспособление')),
                ('avoidance_answer', models.TextField(verbose_name='Избегание')),
                ('compromise_answer', models.TextField(verbose_name='Компромисс')),
                ('cooperation_answer', models.TextField(verbose_name='Сотрудничество')),
            ],
            options={
                'verbose_name': 'ответы',
            },
        ),
        migrations.AlterField(
            model_name='situation',
            name='avoidance',
            field=models.CharField(max_length=50, verbose_name='Избегание'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='compromise',
            field=models.CharField(max_length=50, verbose_name='Компромисс'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='cooperation',
            field=models.CharField(max_length=50, verbose_name='Сотрудничество'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='device',
            field=models.CharField(max_length=50, verbose_name='Приспособление'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='rivalry',
            field=models.CharField(max_length=50, verbose_name='Соперничество'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='situation',
            field=models.CharField(max_length=50, verbose_name='Ситуация'),
        ),
        migrations.AddField(
            model_name='situation',
            name='answers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.answers', verbose_name='Ответы'),
            preserve_default=False,
        ),
    ]
