# Generated by Django 3.2.19 on 2024-11-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20241129_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='answers',
        ),
    ]
