# Generated by Django 3.2.19 on 2024-11-29 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_situation_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name_plural': 'ответы'},
        ),
        migrations.AddField(
            model_name='situation',
            name='answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.answers', verbose_name='Ответы'),
        ),
    ]
