# Generated by Django 3.2.19 on 2024-11-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_answers_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answers',
        ),
    ]
