# Generated by Django 3.2.19 on 2024-11-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_answers_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='answers',
        ),
    ]
