# Generated by Django 3.2.19 on 2024-11-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_situation_answers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
