# Generated by Django 3.2.19 on 2024-12-01 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_delete_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rivalry_answer', models.TextField(verbose_name='Соперничество')),
                ('device_answer', models.TextField(verbose_name='Приспособление')),
                ('avoidance_answer', models.TextField(verbose_name='Избегание')),
                ('compromise_answer', models.TextField(verbose_name='Компромисс')),
                ('cooperation_answer', models.TextField(verbose_name='Сотрудничество')),
            ],
            options={
                'verbose_name_plural': 'ответы',
            },
        ),
        migrations.AddField(
            model_name='situation',
            name='answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.answers', verbose_name='Ответы'),
        ),
    ]
