# Generated by Django 3.2.19 on 2024-12-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20241201_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='answers',
        ),
        migrations.AddField(
            model_name='situation',
            name='avoidance_answer',
            field=models.TextField(blank=True, verbose_name='Ответ на избегание'),
        ),
        migrations.AddField(
            model_name='situation',
            name='compromise_answer',
            field=models.TextField(blank=True, verbose_name='Ответ на компромисс'),
        ),
        migrations.AddField(
            model_name='situation',
            name='cooperation_answer',
            field=models.TextField(blank=True, verbose_name='Ответ на сотрудничество'),
        ),
        migrations.AddField(
            model_name='situation',
            name='device_answer',
            field=models.TextField(blank=True, verbose_name='Ответ на приспособление'),
        ),
        migrations.AddField(
            model_name='situation',
            name='rivalry_answer',
            field=models.TextField(blank=True, verbose_name='Ответ на соперничество'),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
