# Generated by Django 3.2.19 on 2024-12-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20241201_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='situation',
            field=models.TextField(verbose_name='Ситуация'),
        ),
    ]
