# Generated by Django 3.2.19 on 2024-12-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_situation_situation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.TextField(verbose_name='совет')),
            ],
            options={
                'verbose_name_plural': 'советы',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Обратная связь')),
            ],
            options={
                'verbose_name_plural': 'обратная связь',
            },
        ),
    ]
